import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lab 1 - Album</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.h1}>MyTunes</h1>

        <div className={styles.imgAlbumContainer}>
          <div>
            <Image
              src="/new-jeans.jpg"
              width={350}
              height={500}
              alt="New Jeans group image"
            />
          </div>

          <div className={styles.albumSection}>
            <h2 className={styles.h2}>New Jeans' Albums</h2>
            <details className={styles.details}>
              <summary className={styles.summary}>New Jeans</summary>
              1st Mini Album
              <ol className={styles.ol}>
                <li>Attention</li>
                <li>Hype Boy</li>
                <li>Cookie</li>
                <li>Hurt</li>
              </ol>
            </details>
            <details className={styles.details}>
              <summary className={styles.summary}>Get Up</summary>
              2nd EP Album
              <ol className={styles.ol}>
                <li>New Jeans</li>
                <li>Super Shy</li>
                <li>ETA</li>
                <li>Cool With You</li>
                <li>Get Up</li>
                <li>ASAP</li>
              </ol>
            </details>
            <details className={styles.details}>
              <summary className={styles.summary}>NJWMX</summary>
              1st Remix Album
              <ol className={styles.ol}>
                <li>Ditto (250 Remix)</li>
                <li>OMG (FRNK Remix)</li>
                <li>Attention (250 Remix)</li>
                <li>Hype Boy (250 Remix)</li>
                <li>Cookie (FRNK Remix)</li>
                <li>Hurt (250 Remix)</li>
                <li>Ditto (250 Remix) (Inst.)</li>
                <li>OMG (FRNK Remix) (Inst.)</li>
                <li>Attention (250 Remix) (Inst.)</li>
                <li>Hype Boy (250 Remix) (Inst.)</li>
                <li>Cookie (FRNK Remix) (Inst.)</li>
                <li>Hurt (250 Remix) (Inst.)</li>
              </ol>
            </details>
          </div>
        </div>
      </main>
    </>
  );
}
